# Generated by Django 4.2.4 on 2023-10-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_booking_room_type_delete_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
