# Generated by Django 4.2.4 on 2023-10-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_booking_check_out_alter_booking_check_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Single', 'Single Room'), ('Double', 'Double Room')], max_length=20, null=True)),
            ],
        ),
    ]
