# Generated by Django 4.2.4 on 2023-10-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_rooms_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(choices=[('Radisson BLU Hotel', 'Radisson BLU Hotel'), ('Ani Plasa Hotel', 'Ani Plaza Hotel'), ('The Alexander Hotel', 'The Alexander Hotel'), ('Tufenkian Historic Yerevan Hotel', 'Tufenkian Historic Yerevan Hotel')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('Yerevan', 'Yerevan')], max_length=100)),
            ],
        ),
    ]
