# Generated by Django 4.2.4 on 2023-10-08 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_booking_hotel_booking_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='book.hotel'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='book.place'),
        ),
    ]
