# Generated by Django 4.2.4 on 2023-10-16 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_booking_hotel_alter_booking_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.hotel'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.place'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel',
            field=models.CharField(choices=[('Radisson BLU Hotel', 'Radisson BLU Hotel'), ('Ani Plasa Hotel', 'Ani Plaza Hotel'), ('The Alexander Hotel', 'The Alexander Hotel'), ('Tufenkian Historic Yerevan Hotel', 'Tufenkian Historic Yerevan Hotel')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(choices=[('Yerevan', 'Yerevan')], max_length=100, null=True),
        ),
    ]
