# Generated by Django 4.2.4 on 2023-11-03 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_roomprice_remove_booking_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomprice',
            old_name='room_price_choice',
            new_name='room_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='room_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.roomprice'),
        ),
    ]
