# Generated by Django 4.2.4 on 2023-11-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_rename_room_price_choice_roomprice_room_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprice',
            name='room_price',
            field=models.CharField(choices=[(180, '180$'), (300, '300$'), (500, '500$'), (850, '850$')], max_length=50, null=True),
        ),
    ]
