# Generated by Django 4.2.4 on 2023-11-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_alter_roomprice_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprice',
            name='room_price',
            field=models.CharField(choices=[('180', '180$'), ('300', '300$'), ('500', '500$'), ('850', '850$')], max_length=50, null=True),
        ),
    ]
