# Generated by Django 4.2.4 on 2023-11-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_alter_roomprice_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprice',
            name='room_price',
            field=models.CharField(choices=[('Single', '180$'), ('Double', '300$'), ('Deluxe', '500$'), ('Presidential', '850$')], max_length=50, null=True),
        ),
    ]
