# Generated by Django 4.2.4 on 2023-11-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_alter_roomprice_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_price',
        ),
        migrations.DeleteModel(
            name='RoomPrice',
        ),
    ]
